$umask 0000
include(file="/etc/rsyslog.d/*.conf" mode="optional")
# Шаблон для создания папки /var/log/alloy
$template AlloyFile,"/var/log/alloy/combined.log")
*.* action(type="omfile" dynaFile="AlloyFile" dirCreateMode="0755" fileCreateMode="0644")


$template RemoteLogs,"/var/log/rsyslog/%HOSTNAME%/%PROGRAMNAME%.log"
*.* action(type="omfile" dynaFile="RemoteLogs" dirCreateMode="0755" fileCreateMode="0644")
